Vagrant::Config.run do |config|
    config.vm.define :web_server_1 do |config|
      config.vm.box = "lucid32"
      config.vm.network('33.33.33.22')
      config.vm.customize do |vm|
          vm.memory_size = 256
      end
    end
end
